### ISSUE TITLE
Attribute Error on PackTrack and Server Error (500)

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#16]
Hi, 
We were experiencing the Attribute Error, when trying to check this GlobalSat501 packet on Surveyor: 000db537076a397e this morning. Now we are getting Server Error (500). Please check the issue here. 

Thanks!

**Comment by krisdthompson** [comment]
fixed an error on creating an empty dataframe (should be pd.Dataframe() )
Now gettting an error trying to normalize the results set
https://surveyor1.kttex.com/packTrack/packGraph/?endnode=54&start=2024-04-01T00%3A00&end=2024-04-02T16%3A53&submit=Submit
`Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'frame_size'"]`

**Comment by krisdthompson** [comment]
Helium generated traffic lacks "packet_size" and "gps.lat/long"

**Comment by krisdthompson** [comment]
Fixed issue on PackTrack (cast as Int64 not just as int).

However, defect remains on the GeoView
```
ValueError at /geowan/geoview/54/20240401T0456Z/20240402T2149Z/
Point coordinates must be finite. (nan, nan, 0.0) has been passed as coordinates.
```

**Comment by krisdthompson** [comment]
fixed more errors on geoview

**Comment by krisdthompson** [comment]
resolved and deployed
