### ISSUE TITLE
Issue with parameter "Distance" on the device Map view

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#22]
On the Device Map view the distance from the GW is not showing up correctly. Here is how it shows up on the map: 

> Distance:{row['dist']:.2f}km 

When click on the device on the map, this is how the Distance shows up. Here is a device link: https://surveyor.everynet.com/geowan/geoview/160/20240411T0551Z/20240411T2118Z/

**Comment by krisdthompson** [comment]
recreated the defect here:
https://surveyor1.kttex.com/geowan/geoview/160/20240411T0551Z/20240411T2118Z/
fixing.

**Comment by krisdthompson** [comment]
fixed. Need to use F formatted strings.

**Comment by krisdthompson** [comment]
dist_txt = f"Distance:{row['dist']:.2f}km"

**Comment by krisdthompson** [comment]
all fixed and released!
