### ISSUE TITLE
Make the Map Loading Faster

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#35]
The Map loading takes longer time for a large dataset (eg. South Daytona). Is it possible to make it faster?

**Comment by krisdthompson** [comment]
The Map is now being delivered as a Pop-out (new tab). Let's see if it performs better.
This should make it easy to save the HTML map for sharing as well.

**Comment by krisdthompson** [comment]
Testing the new Pop-out map here:
https://surveyor2.everynet.com/performer/bucketDevicesReport/14/mdayt1/20240325T0500Z/20240425T0500Z/
5000 devices and 30 days. May need to load additional locations data.

**Comment by krisdthompson** [comment]
resolved for now
