### ISSUE TITLE
Changes on the PDR graph

### ISSUE THREAD

**Issue by SherwoodArcher** [sheeriot/surveyor#41]
We detected on Brazil, more specifically on the Campinas bucket, that 866 devices only have one uplink, and some of then have a lot of frames. This probably indicates a device issue. However, the graph becomes innacurate. Is possible to remove devices that have only one uplink from the PDR Graph?

![image](https://github.com/sheeriot/surveyor/assets/31456339/f3e5a7aa-762e-483d-8b16-ff8109e2ddbf)

**Comment by krisdthompson** [comment]
this should be easily removed from the graph. You might also want to look at uplinks/day per device as an indicator.

**Comment by krisdthompson** [comment]
This is fixed and deployed to all servers. 
Similar, the PDR map on the surveyor needs also be updated to remove the "100%" and replace it with something else
