### ISSUE TITLE
Pop-up on MAP - Add Gateway count

### ISSUE THREAD

**Issue by SherwoodArcher** [sheeriot/surveyor#43]
![image](https://github.com/sheeriot/surveyor/assets/31456339/7e3d361a-8a40-4a3c-a3ba-bf47840c4297)

Is possible to add number of gateways that are reaching the device?

**Comment by krisdthompson** [comment]
gateway count has been added to the map.
The map got quite a few updated. 
Devices that only show one uplink are marked in red.
One uplink is determined by one unique uplinks counter. Many devices are sending the same uplink over and over again and are reporting as a single uplink.
