### ISSUE TITLE
Map- individual gw metrics indicator on Surveyor Map

### ISSUE THREAD

**Issue by Timkipley** [sheeriot/surveyor#71]
when in Surveyor Map and viewing coverage by individual gateway RSSI Mean, request adjustment in pin/indicator pin that would allow easier viewing of dense populated areas as shown in image below.  Shrinking pin size in relation to colored circle may be sufficient but request ability to see heatmap while zoomed out on a partial city scale.

<img width="891" alt="Screenshot 2024-07-17 at 1 46 37 PM" src="https://github.com/user-attachments/assets/7844ace1-f65d-4fb4-b89d-4b340a114ac7">

**Comment by krisdthompson** [comment]
agreed. Let's rework this "Marker"

**Comment by krisdthompson** [comment]
fixing now

**Comment by krisdthompson** [comment]
this is now fixed. RSSI map uses CircleMarker again
