### ISSUE TITLE
Server Error 500 on Individual Device Report in Bucket Device

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#77]
Hi- 
We are getting Server Error 500, when clicking on individual device link.
here is the link: https://surveyor.everynet.com/performer/bucketDevicesReport/31/None/mavista1/20240728T0500Z/20240729T1418Z/

**Comment by krisdthompson** [comment]
This URL gives a 500 error
https://surveyor.everynet.com/device/bucketdevice/31/mavista1/0c57eb00001084a3/20240728T0500Z/20240729T1418Z/

This is a 500 error on Dev server
https://surveyor1.kttex.com/device/bucketdevice/11/mflo1/0c57eb00000c4553/20240727T0400Z/20240730T1155Z/

**Comment by krisdthompson** [comment]
This is resolved
https://surveyor.everynet.com/device/bucketdevice/31/None/mavista1/0c57eb00000e77a7/20240730T0400Z/20240730T1624Z/

**Comment by krisdthompson** [comment]
fixed
