### ISSUE TITLE
Missing "tag" field on the Device Uplinks report 

### ISSUE THREAD

**Issue by mkhatun1** [sheeriot/surveyor#92]
Hi- Could you please add back the 'tag' field on the Device Uplinks report? Mueller is complaining of not getting the device node_id, they need this to identify the device. Here is an example report showing the missing tag column on the Device Uplinks report file: 
https://surveyor.everynet.com/performer/bucketDevicesReport/48/None/moundsview/20240908T0500Z/20240911T1832Z/
![missing_tags](https://github.com/user-attachments/assets/8a7fec36-5425-47f5-9ab8-98f8123e27b4)

**Comment by krisdthompson** [comment]
Here is a test URL for the Dev server.
https://surveyor1.kttex.com/performer/bucketDevicesReport/39/groupA/altavista/20240905T0400Z/20240912T1004Z/
Tag1 and Tag2 are missing.

**Comment by krisdthompson** [comment]
fixed. Release pending.

**Comment by krisdthompson** [comment]
this is fixed and in production.
